import { WorkPermissions, SystemUserAccount, UserRole } from '../types';

export const ALL_ADMIN_PERMISSIONS: WorkPermissions = {
  canViewDashboard: true,
  canViewFeeCollection: true,
  canViewApprovals: true,
  canViewStudents: true,
  canViewCourses: true,
  canViewExtraFees: true,
  canViewBiometric: true,
  canViewFinances: true,
  canViewParentPortal: true,
  canViewUserPermissions: true,

  canCollectFees: true,
  canApplyDiscountAndCoupons: true,
  canUpgradeCourse: true,
  canCollectExtraFees: true,
  canEditPaymentRecords: true,
  canDeletePaymentRecords: true,
  canPrintReceipts: true,

  canApproveFeePayments: true,
  canRejectFeePayments: true,
  canBatchApprovePayments: true,
  canApproveExtraFees: true,

  canAddStudent: true,
  canEditStudent: true,
  canDeleteStudent: true,
  canImportStudentsCSV: true,
  canExportStudents: true,
  canPrintIDCards: true,
  canIssueScorecards: true,
  canSendWhatsAppReminders: true,

  canAddCourse: true,
  canEditCourse: true,
  canDeleteCourse: true,
  canRestoreCourses: true,

  canRecordBiometricPunches: true,
  canSyncBiometricDevices: true,
  canImportBiometricLogs: true,

  canViewFinancialStatements: true,
  canRecordIncomeExpense: true,
  canEditIncomeExpense: true,
  canApproveIncomeExpense: true,
  canDeleteIncomeExpense: true,

  canEditInstituteSettings: true,
  canManageUPIandBank: true,
  canManageUserPermissions: true,
};

export const DEFAULT_STAFF_PERMISSIONS: WorkPermissions = {
  canViewDashboard: true,
  canViewFeeCollection: true,
  canViewApprovals: true,
  canViewStudents: true,
  canViewCourses: true,
  canViewExtraFees: true,
  canViewBiometric: true,
  canViewFinances: true,
  canViewParentPortal: false,
  canViewUserPermissions: false,

  canCollectFees: true,
  canApplyDiscountAndCoupons: true,
  canUpgradeCourse: true,
  canCollectExtraFees: true,
  canEditPaymentRecords: false,
  canDeletePaymentRecords: false,
  canPrintReceipts: true,

  canApproveFeePayments: false,
  canRejectFeePayments: false,
  canBatchApprovePayments: false,
  canApproveExtraFees: false,

  canAddStudent: true,
  canEditStudent: true,
  canDeleteStudent: false,
  canImportStudentsCSV: true,
  canExportStudents: true,
  canPrintIDCards: true,
  canIssueScorecards: true,
  canSendWhatsAppReminders: true,

  canAddCourse: false,
  canEditCourse: false,
  canDeleteCourse: false,
  canRestoreCourses: false,

  canRecordBiometricPunches: true,
  canSyncBiometricDevices: true,
  canImportBiometricLogs: true,

  canViewFinancialStatements: true,
  canRecordIncomeExpense: true,
  canEditIncomeExpense: false,
  canApproveIncomeExpense: false,
  canDeleteIncomeExpense: false,

  canEditInstituteSettings: false,
  canManageUPIandBank: false,
  canManageUserPermissions: false,
};

export const DEFAULT_STUDENT_PERMISSIONS: WorkPermissions = {
  canViewDashboard: false,
  canViewFeeCollection: false,
  canViewApprovals: false,
  canViewStudents: false,
  canViewCourses: false,
  canViewExtraFees: false,
  canViewBiometric: false,
  canViewFinances: false,
  canViewParentPortal: true,
  canViewUserPermissions: false,

  canCollectFees: false,
  canApplyDiscountAndCoupons: false,
  canUpgradeCourse: false,
  canCollectExtraFees: false,
  canEditPaymentRecords: false,
  canDeletePaymentRecords: false,
  canPrintReceipts: true,

  canApproveFeePayments: false,
  canRejectFeePayments: false,
  canBatchApprovePayments: false,
  canApproveExtraFees: false,

  canAddStudent: false,
  canEditStudent: false,
  canDeleteStudent: false,
  canImportStudentsCSV: false,
  canExportStudents: false,
  canPrintIDCards: true,
  canIssueScorecards: true,
  canSendWhatsAppReminders: false,

  canAddCourse: false,
  canEditCourse: false,
  canDeleteCourse: false,
  canRestoreCourses: false,

  canRecordBiometricPunches: false,
  canSyncBiometricDevices: false,
  canImportBiometricLogs: false,

  canViewFinancialStatements: false,
  canRecordIncomeExpense: false,
  canEditIncomeExpense: false,
  canApproveIncomeExpense: false,
  canDeleteIncomeExpense: false,

  canEditInstituteSettings: false,
  canManageUPIandBank: false,
  canManageUserPermissions: false,
};

export interface PermissionPreset {
  id: string;
  name: string;
  role: UserRole;
  description: string;
  badgeColor: string;
  permissions: Partial<WorkPermissions>;
}

export const PERMISSION_PRESETS: PermissionPreset[] = [
  {
    id: 'super-admin',
    name: 'Super Admin / Director',
    role: 'admin',
    description: 'Full unconstrained system governance, financial approvals, ledger control, and user management.',
    badgeColor: 'bg-indigo-100 text-indigo-700 border-indigo-200',
    permissions: { ...ALL_ADMIN_PERMISSIONS },
  },
  {
    id: 'senior-accountant',
    name: 'Senior Accountant & Counter Head',
    role: 'staff',
    description: 'Fee collection desk, discounts, extra fees, expense recording, and financial statements.',
    badgeColor: 'bg-emerald-100 text-emerald-700 border-emerald-200',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canCollectFees: true,
      canApplyDiscountAndCoupons: true,
      canUpgradeCourse: true,
      canCollectExtraFees: true,
      canRecordIncomeExpense: true,
      canViewFinances: true,
      canViewFinancialStatements: true,
      canAddStudent: true,
      canEditStudent: true,
      canPrintIDCards: true,
      canSendWhatsAppReminders: true,
    },
  },
  {
    id: 'front-desk-reception',
    name: 'Front Desk & Admissions Counter',
    role: 'staff',
    description: 'Student admissions, fee receipt collection, biometric punch logging, and WhatsApp notifications.',
    badgeColor: 'bg-sky-100 text-sky-700 border-sky-200',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canCollectFees: true,
      canApplyDiscountAndCoupons: true,
      canUpgradeCourse: true,
      canCollectExtraFees: true,
      canAddStudent: true,
      canEditStudent: true,
      canImportStudentsCSV: true,
      canPrintIDCards: true,
      canSendWhatsAppReminders: true,
      canRecordBiometricPunches: true,
      canViewFinances: false,
      canRecordIncomeExpense: false,
    },
  },
  {
    id: 'admission-counselor',
    name: 'Admission & Academic Counselor',
    role: 'staff',
    description: 'New admissions, student academic profile management, scorecards, and course counseling.',
    badgeColor: 'bg-purple-100 text-purple-700 border-purple-200',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canViewStudents: true,
      canAddStudent: true,
      canEditStudent: true,
      canImportStudentsCSV: true,
      canPrintIDCards: true,
      canIssueScorecards: true,
      canSendWhatsAppReminders: true,
      canViewCourses: true,
      canViewFeeCollection: false,
      canCollectFees: false,
      canViewFinances: false,
      canRecordIncomeExpense: false,
    },
  },
  {
    id: 'biometric-lab-assistant',
    name: 'Biometric Lab Operator',
    role: 'staff',
    description: 'Biometric device synchronization, hardware punch recording, and student attendance monitoring.',
    badgeColor: 'bg-amber-100 text-amber-700 border-amber-200',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canViewDashboard: true,
      canViewBiometric: true,
      canRecordBiometricPunches: true,
      canSyncBiometricDevices: true,
      canImportBiometricLogs: true,
      canViewStudents: true,
      canAddStudent: false,
      canEditStudent: false,
      canViewFeeCollection: false,
      canCollectFees: false,
      canViewFinances: false,
      canRecordIncomeExpense: false,
    },
  },
];

export const INITIAL_SYSTEM_USERS: SystemUserAccount[] = [
  {
    id: 'user-admin-01',
    loginId: 'admin@digitech.edu',
    password: 'admin@123',
    name: 'Dr. Rajesh Verma',
    role: 'admin',
    roleLabel: 'Institute Director & Super Admin',
    designation: 'Director & Chief Administrator',
    email: 'director@digitechacademy.edu',
    phone: '+91 98765 43210',
    department: 'Management & Governance',
    avatarColor: 'from-indigo-600 to-violet-700',
    status: 'ACTIVE',
    createdAt: '2026-01-01',
    lastLoginAt: 'Today, 09:15 AM',
    permissions: { ...ALL_ADMIN_PERMISSIONS },
    notes: 'Primary Institute Director with permanent master administrative authority.',
  },
  {
    id: 'user-staff-01',
    loginId: 'staff@digitech.edu',
    password: 'staff@123',
    name: 'Sunil Sharma',
    role: 'staff',
    roleLabel: 'Senior Accounts Officer',
    designation: 'Accounts Counter & Admissions Desk',
    email: 'accounts@digitechacademy.edu',
    phone: '+91 98765 43211',
    department: 'Accounts & Billing',
    avatarColor: 'from-emerald-600 to-teal-700',
    status: 'ACTIVE',
    createdAt: '2026-01-10',
    lastLoginAt: 'Today, 10:45 AM',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canCollectFees: true,
      canApplyDiscountAndCoupons: true,
      canUpgradeCourse: true,
      canCollectExtraFees: true,
      canRecordIncomeExpense: true,
      canViewFinances: true,
      canViewFinancialStatements: true,
      canAddStudent: true,
      canEditStudent: true,
      canPrintIDCards: true,
      canSendWhatsAppReminders: true,
    },
    notes: 'Handles high-capacity front counter fee collections, discounts, and ledger entries.',
  },
  {
    id: 'user-staff-02',
    loginId: 'pooja@digitech.edu',
    password: 'staff@123',
    name: 'Pooja Verma',
    role: 'staff',
    roleLabel: 'Front Desk Receptionist',
    designation: 'Front Desk & Student Counselor',
    email: 'pooja@digitechacademy.edu',
    phone: '+91 98765 43212',
    department: 'Admissions & Front Desk',
    avatarColor: 'from-sky-600 to-blue-700',
    status: 'ACTIVE',
    createdAt: '2026-02-01',
    lastLoginAt: 'Yesterday, 04:30 PM',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canCollectFees: true,
      canApplyDiscountAndCoupons: true,
      canUpgradeCourse: true,
      canCollectExtraFees: true,
      canAddStudent: true,
      canEditStudent: true,
      canImportStudentsCSV: true,
      canPrintIDCards: true,
      canSendWhatsAppReminders: true,
      canRecordBiometricPunches: true,
      canViewFinances: false,
      canRecordIncomeExpense: false,
    },
    notes: 'Responsible for inquiry calls, new admissions, and issuing trainee identity cards.',
  },
  {
    id: 'user-staff-03',
    loginId: 'amit@digitech.edu',
    password: 'staff@123',
    name: 'Amit Kumar',
    role: 'staff',
    roleLabel: 'Academic Coordinator',
    designation: 'Academic Counselor & Lab Coordinator',
    email: 'amit@digitechacademy.edu',
    phone: '+91 98765 43214',
    department: 'Academics & Biometric Lab',
    avatarColor: 'from-amber-600 to-orange-700',
    status: 'ACTIVE',
    createdAt: '2026-02-15',
    lastLoginAt: '2 days ago',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canViewStudents: true,
      canAddStudent: true,
      canEditStudent: true,
      canImportStudentsCSV: true,
      canPrintIDCards: true,
      canIssueScorecards: true,
      canSendWhatsAppReminders: true,
      canViewCourses: true,
      canRecordBiometricPunches: true,
      canSyncBiometricDevices: true,
      canImportBiometricLogs: true,
      canViewFeeCollection: false,
      canCollectFees: false,
      canViewFinances: false,
      canRecordIncomeExpense: false,
    },
    notes: 'Manages batch timings, attendance logs, and student performance assessments.',
  },
];

export interface PermissionCategoryMeta {
  id: string;
  title: string;
  iconName: string;
  description: string;
  color: string;
  keys: (keyof WorkPermissions)[];
}

export const PERMISSION_CATEGORIES: PermissionCategoryMeta[] = [
  {
    id: 'navigation',
    title: 'Navigation & Module Visibility',
    iconName: 'LayoutGrid',
    description: 'Control which workspace tabs appear in the main navigation bar.',
    color: 'indigo',
    keys: [
      'canViewDashboard',
      'canViewFeeCollection',
      'canViewApprovals',
      'canViewStudents',
      'canViewCourses',
      'canViewExtraFees',
      'canViewBiometric',
      'canViewFinances',
      'canViewParentPortal',
      'canViewUserPermissions',
    ],
  },
  {
    id: 'fee_collection',
    title: 'Fees Collection & Counter Operations',
    iconName: 'CreditCard',
    description: 'Permissions for recording fees, vouchers, discounts, and upgrades.',
    color: 'emerald',
    keys: [
      'canCollectFees',
      'canApplyDiscountAndCoupons',
      'canUpgradeCourse',
      'canCollectExtraFees',
      'canEditPaymentRecords',
      'canDeletePaymentRecords',
      'canPrintReceipts',
    ],
  },
  {
    id: 'approvals',
    title: 'Approvals & Governance (Admin Level)',
    iconName: 'ShieldCheck',
    description: 'Authority to sanction receipts, clear ledger entries, and batch verify.',
    color: 'purple',
    keys: [
      'canApproveFeePayments',
      'canRejectFeePayments',
      'canBatchApprovePayments',
      'canApproveExtraFees',
    ],
  },
  {
    id: 'admissions',
    title: 'Student Admissions & Academic Directory',
    iconName: 'Users',
    description: 'Manage trainee enrollments, ID cards, CSV imports, and WhatsApp broadcasts.',
    color: 'blue',
    keys: [
      'canAddStudent',
      'canEditStudent',
      'canDeleteStudent',
      'canImportStudentsCSV',
      'canExportStudents',
      'canPrintIDCards',
      'canIssueScorecards',
      'canSendWhatsAppReminders',
    ],
  },
  {
    id: 'courses',
    title: 'Course Catalog & Pricing Management',
    iconName: 'BookOpen',
    description: 'Configure course fees, syllabus, installment models, and course recycling.',
    color: 'amber',
    keys: [
      'canAddCourse',
      'canEditCourse',
      'canDeleteCourse',
      'canRestoreCourses',
    ],
  },
  {
    id: 'biometric',
    title: 'Biometric Attendance & Hardware Desk',
    iconName: 'Fingerprint',
    description: 'Operate fingerprint terminals, sync cloud logs, and manual punch overrides.',
    color: 'teal',
    keys: [
      'canRecordBiometricPunches',
      'canSyncBiometricDevices',
      'canImportBiometricLogs',
    ],
  },
  {
    id: 'finances',
    title: 'Income, Expenses & Financial Cashflow',
    iconName: 'TrendingUp',
    description: 'Track center operating expenditures, direct incomes, and audit vouchers.',
    color: 'rose',
    keys: [
      'canViewFinancialStatements',
      'canRecordIncomeExpense',
      'canEditIncomeExpense',
      'canApproveIncomeExpense',
      'canDeleteIncomeExpense',
    ],
  },
  {
    id: 'system',
    title: 'Institute Master & User Permissions',
    iconName: 'Sliders',
    description: 'Configure institute identity, banking UPI VPAs, and user permissions.',
    color: 'slate',
    keys: [
      'canEditInstituteSettings',
      'canManageUPIandBank',
      'canManageUserPermissions',
    ],
  },
];

export const PERMISSION_LABELS: Record<keyof WorkPermissions, { label: string; desc: string; isHighRisk?: boolean }> = {
  canViewDashboard: { label: 'View Dashboard Tab', desc: 'Access high-level analytics & summary metrics' },
  canViewFeeCollection: { label: 'View Fee Collection Desk', desc: 'Access counter fee collection desk' },
  canViewApprovals: { label: 'View Fee Approvals Tab', desc: 'Access payment verification and approval queue' },
  canViewStudents: { label: 'View Students Tab', desc: 'Access student database and admission roster' },
  canViewCourses: { label: 'View Course Catalog', desc: 'Access course lists and fee structures' },
  canViewExtraFees: { label: 'View Extra Fees Tab', desc: 'Access Form Fillup & Annual Day fee module' },
  canViewBiometric: { label: 'View Biometric Tab', desc: 'Access attendance station and device sync logs' },
  canViewFinances: { label: 'View Income & Expenses Tab', desc: 'Access center financial cashflow ledger' },
  canViewParentPortal: { label: 'View Parent Portal', desc: 'Access student self-service fee portal' },
  canViewUserPermissions: { label: 'View User Permissions Tab', desc: 'Access user and work permissions center' },

  canCollectFees: { label: 'Collect Student Fees', desc: 'Record tuition & installment fee payments' },
  canApplyDiscountAndCoupons: { label: 'Apply Discounts & Coupons', desc: 'Apply promotional coupons and custom fee deductions' },
  canUpgradeCourse: { label: 'Process Course Upgrades', desc: 'Upgrade courses (e.g. OSCIT to OSCIT A+) and carry fees' },
  canCollectExtraFees: { label: 'Collect Extra Fees', desc: 'Collect Form Fillup, Annual Day, and exam charges' },
  canEditPaymentRecords: { label: 'Edit Payment Records', desc: 'Modify existing fee records & voucher metadata', isHighRisk: true },
  canDeletePaymentRecords: { label: 'Delete Payment Records', desc: 'Void or remove payment entries from records', isHighRisk: true },
  canPrintReceipts: { label: 'Print Official Receipts', desc: 'Generate printable receipts and WhatsApp slips' },

  canApproveFeePayments: { label: 'Approve Fee Payments', desc: 'Sanction and seal collected counter receipts into verified income' },
  canRejectFeePayments: { label: 'Reject Fee Submissions', desc: 'Reject invalid counter submissions with reason notes' },
  canBatchApprovePayments: { label: 'Batch Approve Receipts', desc: 'One-click sanction all pending fee submissions' },
  canApproveExtraFees: { label: 'Approve Extra Fees', desc: 'Sanction and clear Form Fillup & Annual Day submissions' },

  canAddStudent: { label: 'Register New Admissions', desc: 'Enroll new students and generate roll numbers' },
  canEditStudent: { label: 'Edit Student Details', desc: 'Modify contact numbers, batch times, and profile data' },
  canDeleteStudent: { label: 'Delete Student Records', desc: 'Permanently remove student profiles from database', isHighRisk: true },
  canImportStudentsCSV: { label: 'Import Students via CSV', desc: 'Bulk upload student lists from Excel/CSV files' },
  canExportStudents: { label: 'Export Student Records', desc: 'Download CSV and Excel roster spreadsheets' },
  canPrintIDCards: { label: 'Generate & Print ID Cards', desc: 'Create and print official student identity cards' },
  canIssueScorecards: { label: 'Issue Academic Scorecards', desc: 'Generate exam performance and assessment reports' },
  canSendWhatsAppReminders: { label: 'Send WhatsApp Reminders', desc: 'Dispatch 1-click overdue and birthday greetings' },

  canAddCourse: { label: 'Create New Courses', desc: 'Add new courses to the institute catalog' },
  canEditCourse: { label: 'Edit Course Fees & Syllabus', desc: 'Update course duration, fees, and curriculum details', isHighRisk: true },
  canDeleteCourse: { label: 'Delete / Recycle Courses', desc: 'Move courses to the recycle bin', isHighRisk: true },
  canRestoreCourses: { label: 'Restore Deleted Courses', desc: 'Recover courses from the recycle bin' },

  canRecordBiometricPunches: { label: 'Record Terminal Punches', desc: 'Perform manual & biometric student clock-ins' },
  canSyncBiometricDevices: { label: 'Sync Biometric Devices', desc: 'Pull real-time punch logs from IP/LAN terminals' },
  canImportBiometricLogs: { label: 'Import Machine Logs', desc: 'Bulk import raw punch logs from CSV/DAT files' },

  canViewFinancialStatements: { label: 'View Financial Statements', desc: 'Inspect monthly revenue, expense breakdowns, and balances' },
  canRecordIncomeExpense: { label: 'Record Income & Expenses', desc: 'Log daily center expenses, petty cash, and direct incomes' },
  canEditIncomeExpense: { label: 'Edit Financial Vouchers', desc: 'Modify financial vouchers and category allocations', isHighRisk: true },
  canApproveIncomeExpense: { label: 'Approve Financial Vouchers', desc: 'Sanction and clear expense vouchers into official balance' },
  canDeleteIncomeExpense: { label: 'Delete Financial Vouchers', desc: 'Void or remove expense entries from financial ledger', isHighRisk: true },

  canEditInstituteSettings: { label: 'Edit Institute Profile', desc: 'Update center name, address, registration, and logo' },
  canManageUPIandBank: { label: 'Manage Banking & UPI VPAs', desc: 'Configure bank account numbers and QR code UPI IDs', isHighRisk: true },
  canManageUserPermissions: { label: 'Manage User & Work Permissions', desc: 'Configure staff access, role presets, and security policies', isHighRisk: true },
};

export function countActivePermissions(permissions?: WorkPermissions): { active: number; total: number } {
  if (!permissions) return { active: 0, total: Object.keys(PERMISSION_LABELS).length };
  const total = Object.keys(PERMISSION_LABELS).length;
  const active = Object.values(permissions).filter(Boolean).length;
  return { active, total };
}

export const DEFAULT_SYSTEM_USERS: SystemUserAccount[] = [
  {
    id: 'user-admin-01',
    loginId: 'admin@digitech.edu',
    password: 'admin@123',
    name: 'Dr. Rajesh Verma',
    role: 'admin',
    roleLabel: 'Institute Director / Super Admin',
    designation: 'Director & Chief Administrator',
    department: 'Executive Management',
    email: 'director@digitech.edu',
    phone: '+91 98765 43210',
    avatarColor: 'from-indigo-600 to-violet-700',
    status: 'ACTIVE',
    createdAt: '2025-01-01',
    lastLoginAt: 'Just now',
    notes: 'Super Admin with absolute authority across fees audit, bank configurations, and staff access control.',
    permissions: { ...ALL_ADMIN_PERMISSIONS },
  },
  {
    id: 'user-staff-01',
    loginId: 'staff@digitech.edu',
    password: 'staff@123',
    name: 'Sunil Sharma',
    role: 'staff',
    roleLabel: 'Accounts & Front Desk Staff',
    designation: 'Accounts Counter Officer',
    department: 'Admissions & Counter',
    email: 'sunil.sharma@digitech.edu',
    phone: '+91 94371 88201',
    avatarColor: 'from-emerald-600 to-teal-700',
    status: 'ACTIVE',
    createdAt: '2025-02-15',
    lastLoginAt: 'Today at 09:30 AM',
    notes: 'Front-desk counter operations. Collects tuition and extra fees, issues provisional receipts. Cannot approve fees.',
    permissions: { ...DEFAULT_STAFF_PERMISSIONS },
  },
  {
    id: 'user-staff-02',
    loginId: 'pooja.verma@digitech.edu',
    password: 'staff@123',
    name: 'Pooja Verma',
    role: 'staff',
    roleLabel: 'Admissions & Counseling Staff',
    designation: 'Admission Counselor',
    department: 'Student Counseling',
    email: 'pooja.counselor@digitech.edu',
    phone: '+91 98612 34567',
    avatarColor: 'from-sky-600 to-cyan-700',
    status: 'ACTIVE',
    createdAt: '2025-04-10',
    lastLoginAt: 'Yesterday at 04:15 PM',
    notes: 'Handles new student inquiries, counseling, batch allotments, and scorecard distribution.',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canCollectFees: false,
      canRecordIncomeExpense: false,
      canEditIncomeExpense: false,
      canApproveIncomeExpense: false,
      canDeleteIncomeExpense: false,
    },
  },
  {
    id: 'user-staff-03',
    loginId: 'amit.lab@digitech.edu',
    password: 'staff@123',
    name: 'Amit Kumar',
    role: 'staff',
    roleLabel: 'Biometric Lab Operator',
    designation: 'Lab Instructor & Biometric Tech',
    department: 'Computer Hardware & Labs',
    email: 'amit.lab@digitech.edu',
    phone: '+91 91234 56789',
    avatarColor: 'from-amber-600 to-orange-700',
    status: 'ACTIVE',
    createdAt: '2025-06-01',
    lastLoginAt: 'Today at 08:45 AM',
    notes: 'Responsible for biometric machines, student machine enrollments, and terminal attendance sync.',
    permissions: {
      ...DEFAULT_STAFF_PERMISSIONS,
      canCollectFees: false,
      canAddStudent: false,
      canEditStudent: false,
      canDeleteStudent: false,
      canRecordIncomeExpense: false,
      canEditIncomeExpense: false,
    },
  },
];

