import {
  Course,
  Student,
  FeePayment,
  BiometricAttendanceRecord,
  BiometricDevice,
  IncomeExpenseItem,
  InstituteSettings,
  WhatsAppTemplate,
  CouponCode,
  ExtraFeePayment,
} from './types';

export const INITIAL_INSTITUTE_SETTINGS: InstituteSettings = {
  name: 'Computer Institute ERP System',
  tagline: 'Premier Institute of IT, Programming & Advanced Accounting',
  regNo: 'REG/GOVT/IT/2018/9842',
  isoCertified: 'ISO 9001:2015 Certified Educational Institute',
  address: 'Plot No. 42, 2nd Floor, IT Knowledge Park, Near Metro Gate 3',
  city: 'New Delhi, 110092',
  phone: '+91 98765 43210',
  whatsappSupport: '919876543210',
  email: 'admissions@computer-institute-erp.edu',
  website: 'www.computer-institute-erp.edu',
  gstNo: '07AAAAA0000A1Z5',
  upiId: 'institute.erp@icici',
  bankName: 'ICICI Bank Ltd',
  accountNo: '629805012345',
  ifscCode: 'ICIC0006298',
  directorName: 'Er. Alok Ranjan',
  directorTitle: 'Director & Center Head',
  studentIdPrefix: 'SRIIT',
  studentIdDigits: 4,
  nextStudentIdNumber: 15,
};

export const INITIAL_COURSES: Course[] = [
  {
    id: 'c-oscit',
    code: 'OSCIT',
    name: 'OSCIT (Odisha State Certificate in Information Technology)',
    duration: '3 Months',
    fee: 4000,
    category: 'Certificate',
    description: 'Computer Fundamentals, Windows 11, MS Word, Excel, PowerPoint, Internet & Typing',
    isUpgradable: true,
  },
  {
    id: 'c-oscit-a',
    code: 'OSCIT-A',
    name: 'OSCIT A (Advanced Certificate in IT & Applications)',
    duration: '4 Months',
    fee: 9500,
    category: 'Advanced Certificate',
    description: 'Advanced MS Office 365, Tally Prime Basics, GST Invoicing, Internet Security & DTP Basics',
    isUpgradable: true,
  },
  {
    id: 'c-oscit-aplus',
    code: 'OSCIT-A+',
    name: 'OSCIT A+ (Professional Master Diploma in Computer Applications)',
    duration: '8 Months',
    fee: 19500,
    category: 'Master Diploma',
    description: 'Comprehensive IT Suite: Office Suite, Tally Prime + GST, DTP Graphic Design, Web Development & AI Tools',
    isUpgradable: false, // Terminal Master Diploma - highest in OSCIT hierarchy
  },
  {
    id: 'c-ococ-tally',
    code: 'OCOC-TALLY',
    name: 'OCOC Tally Prime',
    duration: '2 Months',
    fee: 5000,
    category: 'Accounting',
    description: 'Official OCOC Tally Prime Certificate: Computerized Accounting, Inventory, GST Invoicing, e-Way Bills & Tax Compliance.',
    isUpgradable: false, // Standalone OCOC Certificate (Non-upgradable)
  },
  {
    id: 'c-adca',
    code: 'ADCA-12M',
    name: 'ADCA (Advanced Diploma in Computer Applications)',
    duration: '12 Months',
    fee: 18000,
    category: 'Diploma',
    description: 'Fundamental, MS Office 365, Tally Prime + GST, DTP (Photoshop/CorelDraw), Web Design & C++',
  },
  {
    id: 'c-dca',
    code: 'DCA-06M',
    name: 'DCA (Diploma in Computer Applications)',
    duration: '6 Months',
    fee: 10500,
    category: 'Diploma',
    description: 'Computer Fundamentals, Windows 11, MS Word, Excel, PowerPoint, Internet & Typing',
  },
  {
    id: 'c-tally',
    code: 'TALLY-03M',
    name: 'Tally Prime Professional with e-Way Bill & GST Portal',
    duration: '3 Months',
    fee: 8500,
    category: 'Accounting',
    description: 'Voucher Entry, Inventory, Payroll, GST Reconciliation, TDS, BRS & Balance Sheet Finalization',
  },
  {
    id: 'c-fsd',
    code: 'FSD-06M',
    name: 'Full Stack Web Development (React, Node, MongoDB)',
    duration: '6 Months',
    fee: 32000,
    category: 'Programming',
    description: 'HTML5, Modern CSS/Tailwind, JavaScript ES6+, React, Node.js, Express, REST APIs, Git & Cloud',
  },
  {
    id: 'c-python',
    code: 'PY-04M',
    name: 'Python Programming, Data Science & AI Essentials',
    duration: '4 Months',
    fee: 22000,
    category: 'AI & Data Science',
    description: 'Core Python, OOPs, NumPy, Pandas, Matplotlib, Machine Learning Scikit-Learn & Gemini AI API',
  },
  {
    id: 'c-gd',
    code: 'GDES-04M',
    name: 'Graphic Design Masterclass (Photoshop, Illustrator, Canva)',
    duration: '4 Months',
    fee: 14000,
    category: 'Designing',
    description: 'Photo retouching, Logo branding, Social Media Creatives, Vector illustration, UI prototyping',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu-01',
    rollNo: 'SRIIT0011',
    biometricId: '101',
    name: 'Rahul Sharma',
    fatherName: 'Mr. Satish Sharma',
    motherName: 'Mrs. Sunita Sharma',
    email: 'rahul.sharma@gmail.com',
    phone: '9876543101',
    parentPhone: '9811122331',
    courseId: 'c-adca',
    courseName: 'ADCA (Advanced Diploma in Computer Applications)',
    courseDuration: '12 Months',
    courseEndDate: '2027-01-10',
    academicStatus: 'IN_PROGRESS',
    batchTime: '08:00 AM - 10:00 AM (Morning)',
    admissionDate: '2026-01-10',
    totalFee: 18000,
    discount: 1000,
    netPayableFee: 17000,
    paidAmount: 11000,
    pendingAmount: 6000,
    status: 'active',
    address: 'B-14, Laxmi Nagar, New Delhi',
    installments: [
      { installmentNo: 1, installmentTitle: 'Admission Fees', amount: 6000, dueDate: '2026-01-10', status: 'paid', paidDate: '2026-01-10', receiptId: 'REC-2026-0101' },
      { installmentNo: 2, installmentTitle: '2nd Installment', amount: 5000, dueDate: '2026-02-10', status: 'paid', paidDate: '2026-02-12', receiptId: 'REC-2026-0182' },
      { installmentNo: 3, installmentTitle: '3rd Installment', amount: 6000, dueDate: '2026-03-10', status: 'overdue' },
    ],
  },
  {
    id: 'stu-02',
    rollNo: 'SRIIT0012',
    biometricId: '102',
    name: 'Priya Verma',
    fatherName: 'Mr. Manoj Verma',
    motherName: 'Mrs. Rekha Verma',
    email: 'priya.verma22@gmail.com',
    phone: '9876543102',
    parentPhone: '9822233442',
    courseId: 'c-tally',
    courseName: 'Tally Prime Professional with e-Way Bill & GST Portal',
    courseDuration: '3 Months',
    courseEndDate: '2026-05-01',
    academicStatus: 'EXAM_PASSED',
    examPassedDate: '2026-05-15',
    certificateNo: 'CERT-SRIIT-2026-0012',
    certificateCollectedDate: '2026-05-20',
    batchTime: '10:00 AM - 12:00 PM (Batch A)',
    admissionDate: '2026-02-01',
    totalFee: 8500,
    discount: 500,
    netPayableFee: 8000,
    paidAmount: 8000,
    pendingAmount: 0,
    status: 'active',
    address: 'H-55, Preet Vihar, Delhi',
    installments: [
      { installmentNo: 1, installmentTitle: 'Admission Fees', amount: 4000, dueDate: '2026-02-01', status: 'paid', paidDate: '2026-02-01', receiptId: 'REC-2026-0145' },
      { installmentNo: 2, installmentTitle: '2nd Installment', amount: 4000, dueDate: '2026-03-01', status: 'paid', paidDate: '2026-03-02', receiptId: 'REC-2026-0205' },
    ],
  },
  {
    id: 'stu-03',
    rollNo: 'SRIIT0013',
    biometricId: '103',
    name: 'Aman Khan',
    fatherName: 'Mr. Zahir Khan',
    motherName: 'Mrs. Fatima Khan',
    email: 'aman.khan.tech@gmail.com',
    phone: '9876543103',
    parentPhone: '9833344553',
    courseId: 'c-fsd',
    courseName: 'Full Stack Web Development (React, Node, MongoDB)',
    courseDuration: '6 Months',
    courseEndDate: '2026-07-15',
    academicStatus: 'COURSE_ENDED',
    batchTime: '04:00 PM - 06:00 PM (Evening)',
    admissionDate: '2026-01-15',
    totalFee: 32000,
    discount: 2000,
    netPayableFee: 30000,
    paidAmount: 20000,
    pendingAmount: 10000,
    status: 'active',
    address: 'Pocket C-4, Mayur Vihar Phase 1, Delhi',
    installments: [
      { installmentNo: 1, installmentTitle: 'Admission Fees', amount: 10000, dueDate: '2026-01-15', status: 'paid', paidDate: '2026-01-15', receiptId: 'REC-2026-0112' },
      { installmentNo: 2, installmentTitle: '2nd Installment', amount: 10000, dueDate: '2026-02-15', status: 'paid', paidDate: '2026-02-16', receiptId: 'REC-2026-0199' },
      { installmentNo: 3, installmentTitle: '3rd Installment', amount: 10000, dueDate: '2026-03-25', status: 'pending' },
    ],
  },
  {
    id: 'stu-04',
    rollNo: 'SRIIT0014',
    biometricId: '104',
    name: 'Sneha Patel',
    fatherName: 'Mr. Bhupendra Patel',
    motherName: 'Mrs. Meena Patel',
    email: 'sneha.patel99@gmail.com',
    phone: '9876543104',
    parentPhone: '9844455664',
    courseId: 'c-python',
    courseName: 'Python Programming, Data Science & AI Essentials',
    courseDuration: '4 Months',
    courseEndDate: '2026-06-10',
    academicStatus: 'EXAM_FAILED_REATTEMPT',
    formFillupRequired: true,
    formFillupReason: 'Python Core & Data Science Re-attempt Examination',
    batchTime: '02:00 PM - 04:00 PM (Afternoon)',
    admissionDate: '2026-02-10',
    totalFee: 22000,
    discount: 1000,
    netPayableFee: 21000,
    paidAmount: 7000,
    pendingAmount: 14000,
    status: 'active',
    address: 'G-12, Shakarpur, Delhi',
    installments: [
      { installmentNo: 1, installmentTitle: 'Admission Fees', amount: 7000, dueDate: '2026-02-10', status: 'paid', paidDate: '2026-02-10', receiptId: 'REC-2026-0160' },
      { installmentNo: 2, installmentTitle: '2nd Installment', amount: 7000, dueDate: '2026-03-10', status: 'overdue' },
      { installmentNo: 3, installmentTitle: '3rd Installment', amount: 7000, dueDate: '2026-04-10', status: 'pending' },
    ],
  },
  {
    id: 'stu-05',
    rollNo: 'DTC-2026-105',
    biometricId: '105',
    name: 'Vikram Singh',
    fatherName: 'Mr. Rajendra Singh',
    motherName: 'Mrs. Shanti Devi',
    email: 'vikram.singh.des@gmail.com',
    phone: '9876543105',
    parentPhone: '9855566775',
    courseId: 'c-gd',
    courseName: 'Graphic Design Masterclass (Photoshop, Illustrator, Canva)',
    batchTime: '12:00 PM - 02:00 PM (Noon)',
    admissionDate: '2026-03-01',
    totalFee: 14000,
    discount: 0,
    netPayableFee: 14000,
    paidAmount: 7000,
    pendingAmount: 7000,
    status: 'active',
    address: 'Flat 302, Patparganj, Delhi',
    installments: [
      { installmentNo: 1, amount: 7000, dueDate: '2026-03-01', status: 'paid', paidDate: '2026-03-01', receiptId: 'REC-2026-0210' },
      { installmentNo: 2, amount: 7000, dueDate: '2026-04-01', status: 'pending' },
    ],
  },
  {
    id: 'stu-06',
    rollNo: 'DTC-2026-106',
    biometricId: '106',
    name: 'Anjali Gupta',
    fatherName: 'Mr. Dinesh Gupta',
    motherName: 'Mrs. Suman Gupta',
    email: 'anjali.gupta@gmail.com',
    phone: '9876543106',
    parentPhone: '9866677886',
    courseId: 'c-dca',
    courseName: 'DCA (Diploma in Computer Applications)',
    batchTime: '08:00 AM - 10:00 AM (Morning)',
    admissionDate: '2026-02-15',
    totalFee: 10500,
    discount: 500,
    netPayableFee: 10000,
    paidAmount: 5000,
    pendingAmount: 5000,
    status: 'active',
    address: 'House 88, Nirman Vihar, Delhi',
    installments: [
      { installmentNo: 1, amount: 5000, dueDate: '2026-02-15', status: 'paid', paidDate: '2026-02-15', receiptId: 'REC-2026-0178' },
      { installmentNo: 2, amount: 5000, dueDate: '2026-03-15', status: 'overdue' },
    ],
  },
  {
    id: 'stu-07',
    rollNo: 'DTC-2026-107',
    biometricId: '107',
    name: 'Subhashree Dash',
    fatherName: 'Mr. Kailash Dash',
    motherName: 'Mrs. Minati Dash',
    dob: '2005-09-20', // Celebrating Birthday Today!
    email: 'subhashree.dash@gmail.com',
    phone: '9876543107',
    parentPhone: '9877788997',
    courseId: 'c-oscit',
    courseName: 'OSCIT (Odisha State Certificate in Information Technology)',
    batchTime: '10:00 AM - 12:00 PM (Batch A)',
    admissionDate: '2026-03-01',
    totalFee: 4000,
    discount: 0,
    netPayableFee: 4000,
    paidAmount: 3000,
    pendingAmount: 1000,
    status: 'active',
    address: 'Plot 104, Shaheed Nagar, Bhubaneswar',
    installments: [
      { installmentNo: 1, amount: 3000, dueDate: '2026-03-01', status: 'paid', paidDate: '2026-03-01', receiptId: 'REC-2026-0220' },
      { installmentNo: 2, amount: 1000, dueDate: '2026-04-01', status: 'pending' },
    ],
  },
];

export const INITIAL_COUPONS: CouponCode[] = [
  {
    code: 'OSCIT500',
    discountType: 'flat',
    discountValue: 500,
    description: '₹500 instant concession on OSCIT certificate courses',
    minCourseFee: 4000,
  },
  {
    code: 'DIWALI1000',
    discountType: 'flat',
    discountValue: 1000,
    description: '₹1,000 Special Festive Season Discount',
    minCourseFee: 8000,
  },
  {
    code: 'EARLYBIRD',
    discountType: 'flat',
    discountValue: 1500,
    description: '₹1,500 Early Bird Admission Rebate',
    minCourseFee: 9500,
  },
  {
    code: 'MERIT10',
    discountType: 'percentage',
    discountValue: 10,
    description: '10% Merit Academic Scholarship',
  },
  {
    code: 'DIRECTOR2000',
    discountType: 'flat',
    discountValue: 2000,
    description: '₹2,000 Director Discretionary Concession',
    minCourseFee: 15000,
  },
];

export const INITIAL_FEE_PAYMENTS: FeePayment[] = [
  {
    id: 'rec-01',
    receiptNo: 'REC-2026-0101',
    studentId: 'stu-01',
    studentName: 'Rahul Sharma',
    studentRollNo: 'DTC-2026-101',
    courseName: 'ADCA (Advanced Diploma in Computer Applications)',
    amount: 6000,
    paymentMode: 'cash',
    date: '2026-01-10',
    time: '10:30 AM',
    collectedByStaffId: 'staff-01',
    collectedByStaffName: 'Pooja Verma (Accountant)',
    approvalStatus: 'APPROVED',
    approvedByAdminId: 'admin-01',
    approvedByAdminName: 'Er. Alok Ranjan (Director)',
    approvalDate: '2026-01-10 05:00 PM',
    installmentNos: [1],
    remainingBalanceAfter: 11000,
    remarks: 'First installment at admission time. Cash deposited in counter cashbox.',
  },
  {
    id: 'rec-02',
    receiptNo: 'REC-2026-0182',
    studentId: 'stu-01',
    studentName: 'Rahul Sharma',
    studentRollNo: 'DTC-2026-101',
    courseName: 'ADCA (Advanced Diploma in Computer Applications)',
    amount: 5000,
    paymentMode: 'upi',
    transactionRef: 'UPI/20260212/87623918',
    date: '2026-02-12',
    time: '11:15 AM',
    collectedByStaffId: 'staff-01',
    collectedByStaffName: 'Pooja Verma (Accountant)',
    approvalStatus: 'APPROVED',
    approvedByAdminId: 'admin-01',
    approvedByAdminName: 'Er. Alok Ranjan (Director)',
    approvalDate: '2026-02-12 06:10 PM',
    installmentNos: [2],
    remainingBalanceAfter: 6000,
    remarks: 'Second installment received via Google Pay QR.',
  },
  {
    id: 'rec-03',
    receiptNo: 'REC-2026-0205',
    studentId: 'stu-02',
    studentName: 'Priya Verma',
    studentRollNo: 'DTC-2026-102',
    courseName: 'Tally Prime Professional with e-Way Bill & GST Portal',
    amount: 4000,
    paymentMode: 'upi',
    transactionRef: 'UPI/20260302/99001122',
    date: '2026-03-02',
    time: '02:40 PM',
    collectedByStaffId: 'staff-02',
    collectedByStaffName: 'Ramesh Sharma (Front Desk)',
    approvalStatus: 'APPROVED',
    approvedByAdminId: 'admin-01',
    approvedByAdminName: 'Er. Alok Ranjan (Director)',
    approvalDate: '2026-03-02 07:00 PM',
    installmentNos: [2],
    remainingBalanceAfter: 0,
    remarks: 'Final installment cleared. Full course fees paid.',
  },
  // PENDING APPROVAL - specifically for user testing "staff collect fees then admin approved that"
  {
    id: 'rec-04',
    receiptNo: 'REC-2026-0245',
    studentId: 'stu-04',
    studentName: 'Sneha Patel',
    studentRollNo: 'DTC-2026-104',
    courseName: 'Python Programming, Data Science & AI Essentials',
    amount: 7000,
    paymentMode: 'cash',
    date: '2026-03-18',
    time: '11:45 AM',
    collectedByStaffId: 'staff-01',
    collectedByStaffName: 'Pooja Verma (Accountant)',
    approvalStatus: 'PENDING_APPROVAL',
    installmentNos: [2],
    remainingBalanceAfter: 7000,
    remarks: 'Student paid Cash at front desk. Cash envelope submitted in Accounts safe box. Pending Admin verification.',
  },
  {
    id: 'rec-05',
    receiptNo: 'REC-2026-0246',
    studentId: 'stu-06',
    studentName: 'Anjali Gupta',
    studentRollNo: 'DTC-2026-106',
    courseName: 'DCA (Diploma in Computer Applications)',
    amount: 2500,
    paymentMode: 'upi',
    transactionRef: 'UPI/20260319/44889922',
    date: '2026-03-19',
    time: '03:10 PM',
    collectedByStaffId: 'staff-02',
    collectedByStaffName: 'Ramesh Sharma (Front Desk)',
    approvalStatus: 'PENDING_APPROVAL',
    installmentNos: [2],
    remainingBalanceAfter: 2500,
    remarks: 'Partial payment of 2nd installment via PhonePe. Bank statement reconciliation required by Admin.',
  },
];

export const INITIAL_BIOMETRIC_DEVICES: BiometricDevice[] = [
  {
    id: 'dev-01',
    name: 'Lab 1 - Main Biometric Terminal',
    model: 'ZKTeco K40 Pro (Optical Fingerprint & RFID)',
    ipAddress: '192.168.1.201',
    port: 4370,
    status: 'ONLINE',
    lastSyncTime: 'Just now (Auto-sync 2 min ago)',
    totalLogsToday: 42,
  },
  {
    id: 'dev-02',
    name: 'Reception Gate Terminal',
    model: 'eSSL SilkBio-101 (Multi-Biometric Fingerprint + Face)',
    ipAddress: '192.168.1.202',
    port: 4370,
    status: 'ONLINE',
    lastSyncTime: '5 minutes ago',
    totalLogsToday: 38,
  },
];

export const INITIAL_BIOMETRIC_LOGS: BiometricAttendanceRecord[] = [
  {
    id: 'bio-log-01',
    studentId: 'stu-01',
    studentName: 'Rahul Sharma',
    studentRollNo: 'DTC-2026-101',
    biometricId: '101',
    date: '2026-03-20',
    punchInTime: '07:54:12 AM',
    punchOutTime: '09:58:30 AM',
    status: 'PRESENT',
    deviceId: 'dev-01',
    verificationType: 'FINGERPRINT',
  },
  {
    id: 'bio-log-02',
    studentId: 'stu-02',
    studentName: 'Priya Verma',
    studentRollNo: 'DTC-2026-102',
    biometricId: '102',
    date: '2026-03-20',
    punchInTime: '09:55:04 AM',
    punchOutTime: '11:58:19 AM',
    status: 'PRESENT',
    deviceId: 'dev-01',
    verificationType: 'FINGERPRINT',
  },
  {
    id: 'bio-log-03',
    studentId: 'stu-03',
    studentName: 'Aman Khan',
    studentRollNo: 'DTC-2026-103',
    biometricId: '103',
    date: '2026-03-20',
    punchInTime: '04:12:35 PM',
    status: 'LATE',
    deviceId: 'dev-02',
    verificationType: 'FACE',
  },
  {
    id: 'bio-log-04',
    studentId: 'stu-04',
    studentName: 'Sneha Patel',
    studentRollNo: 'DTC-2026-104',
    biometricId: '104',
    date: '2026-03-20',
    punchInTime: '01:58:10 PM',
    punchOutTime: '04:02:45 PM',
    status: 'PRESENT',
    deviceId: 'dev-01',
    verificationType: 'FINGERPRINT',
  },
  {
    id: 'bio-log-05',
    studentId: 'stu-05',
    studentName: 'Vikram Singh',
    studentRollNo: 'DTC-2026-105',
    biometricId: '105',
    date: '2026-03-20',
    punchInTime: '12:02:40 PM',
    status: 'PRESENT',
    deviceId: 'dev-02',
    verificationType: 'FINGERPRINT',
  },
];

export const INITIAL_INCOME_EXPENSE: IncomeExpenseItem[] = [
  {
    id: 'ie-01',
    type: 'INCOME',
    category: 'Course Fee Collection',
    amount: 6000,
    date: '2026-01-10',
    paymentMode: 'cash',
    referenceId: 'REC-2026-0101',
    title: 'Admission Fee - Rahul Sharma (ADCA)',
    recordedBy: 'Pooja Verma (Accountant)',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-02',
    type: 'INCOME',
    category: 'Course Fee Collection',
    amount: 5000,
    date: '2026-02-12',
    paymentMode: 'upi',
    referenceId: 'REC-2026-0182',
    title: 'Installment 2 - Rahul Sharma (ADCA)',
    recordedBy: 'Pooja Verma (Accountant)',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-03',
    type: 'INCOME',
    category: 'Course Fee Collection',
    amount: 4000,
    date: '2026-03-02',
    paymentMode: 'upi',
    referenceId: 'REC-2026-0205',
    title: 'Final Installment - Priya Verma (Tally)',
    recordedBy: 'Ramesh Sharma (Staff)',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-04',
    type: 'INCOME',
    category: 'Study Material & Books',
    amount: 3200,
    date: '2026-03-05',
    paymentMode: 'cash',
    title: 'Tally Prime Workbook & Lab Practice Manuals (8 Sets)',
    recordedBy: 'Pooja Verma',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-05',
    type: 'EXPENSE',
    category: 'Center Rent',
    amount: 25000,
    date: '2026-03-01',
    paymentMode: 'bank_transfer',
    referenceId: 'RENT-MARCH-2026',
    title: 'Institute Premises Monthly Rent - 2nd Floor IT Wing',
    recordedBy: 'Er. Alok Ranjan (Director)',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-06',
    type: 'EXPENSE',
    category: 'Electricity & Lab Power',
    amount: 7850,
    date: '2026-03-04',
    paymentMode: 'upi',
    referenceId: 'BSES-BILL-98213',
    title: 'Lab 1 & Lab 2 AC + 30 PC Workstations Power Bill',
    recordedBy: 'Pooja Verma',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-07',
    type: 'EXPENSE',
    category: 'Faculty & Staff Salaries',
    amount: 42000,
    date: '2026-03-05',
    paymentMode: 'bank_transfer',
    referenceId: 'SAL-MAR-2026',
    title: 'Web Dev & Python Faculty Remuneration',
    recordedBy: 'Er. Alok Ranjan (Director)',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-08',
    type: 'EXPENSE',
    category: 'Internet & Networking',
    amount: 2400,
    date: '2026-03-08',
    paymentMode: 'upi',
    referenceId: 'AIRTEL-FIBER-500M',
    title: 'Airtel Xstream Fiber 500 Mbps Static IP Line for Computer Lab',
    recordedBy: 'Ramesh Sharma',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-09',
    type: 'EXPENSE',
    category: 'Hardware & Maintenance',
    amount: 3500,
    date: '2026-03-12',
    paymentMode: 'cash',
    referenceId: 'INV-COMP-449',
    title: 'RAM Upgrade (8GB DDR4 x 2) & SSD Replacement in Lab 1',
    recordedBy: 'Ramesh Sharma',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-10',
    type: 'EXPENSE',
    category: 'Marketing & Pamphlets',
    amount: 4500,
    date: '2026-03-14',
    paymentMode: 'cash',
    referenceId: 'PRINT-PAMPHLET-2026',
    title: 'Summer Crash Course Banners & Color Handouts distribution',
    recordedBy: 'Pooja Verma',
    approvedStatus: 'APPROVED',
  },
  {
    id: 'ie-11',
    type: 'EXPENSE',
    category: 'Hardware & Maintenance',
    amount: 2850,
    date: '2026-03-18',
    paymentMode: 'upi',
    referenceId: 'BILL-TECH-992',
    title: 'Lab 2 USB Optical Mice & Keyboard Replacements (10 Sets)',
    recordedBy: 'Ramesh Sharma (Staff)',
    approvedStatus: 'PENDING_APPROVAL',
  },
  {
    id: 'ie-12',
    type: 'INCOME',
    category: 'Study Material & Books',
    amount: 3600,
    date: '2026-03-19',
    paymentMode: 'cash',
    referenceId: 'BOOK-SALE-104',
    title: 'OSCIT & Tally Prime Official Practical Exercise Manuals Sold',
    recordedBy: 'Pooja Verma (Counter)',
    approvedStatus: 'PENDING_APPROVAL',
  },
];

export const INITIAL_EXTRA_FEE_PAYMENTS: ExtraFeePayment[] = [
  {
    id: 'xf-01',
    receiptNo: 'XREC-2026-0001',
    studentId: 'stu-04',
    studentRollNo: 'SRIIT0014',
    studentName: 'Sneha Patel',
    courseName: 'Python Programming, Data Science & AI Essentials',
    feeCategory: 'FORM_FILLUP',
    feeType: 'FORM_FILLUP',
    feeTitle: 'Semester Examination Re-Attempt Form Fillup 2026',
    feeTypeName: 'Semester Examination Re-Attempt Form Fillup 2026',
    amount: 500,
    paymentMode: 'upi',
    transactionRef: 'UPI/982341209844',
    date: '2026-03-19',
    time: '11:30 AM',
    academicYear: '2026',
    sessionOrEventYear: 'Session 2026-27',
    remarks: 'Re-attempt Examination Form Fillup Fee for Module 2 Python Final Test',
    collectedByStaffName: 'Pooja Verma (Counter)',
    collectedByStaffId: 'staff-01',
    approvalStatus: 'PENDING_APPROVAL',
  },
  {
    id: 'xf-02',
    receiptNo: 'XREC-2026-0002',
    studentId: 'stu-01',
    studentRollNo: 'SRIIT0011',
    studentName: 'Rahul Sharma',
    courseName: 'ADCA (Advanced Diploma in Computer Applications)',
    feeCategory: 'ANNUAL_DAY',
    feeType: 'ANNUAL_DAY',
    feeTitle: 'Annual Cultural Day & Sports Fest Delegate Pass 2026',
    feeTypeName: 'Annual Cultural Day & Sports Fest Delegate Pass 2026',
    amount: 1000,
    paymentMode: 'cash',
    date: '2026-03-10',
    time: '02:15 PM',
    academicYear: '2026',
    sessionOrEventYear: 'Session 2026-27',
    remarks: 'Annual Day Celebrations & Cultural Fest Delegate Registration Kit',
    collectedByStaffName: 'Pooja Verma (Counter)',
    collectedByStaffId: 'staff-01',
    approvalStatus: 'APPROVED',
    approvedByAdminId: 'admin-01',
    approvedByAdminName: 'Dr. Rajeshwar Patra (Director)',
    approvalDate: '2026-03-10 05:30 PM',
  },
  {
    id: 'xf-03',
    receiptNo: 'XREC-2026-0003',
    studentId: 'stu-02',
    studentRollNo: 'SRIIT0012',
    studentName: 'Priya Verma',
    courseName: 'Tally Prime Professional with e-Way Bill & GST Portal',
    feeCategory: 'ANNUAL_DAY',
    feeType: 'ANNUAL_DAY',
    feeTitle: 'Annual Day Kit & Prize Distribution Gala Entry',
    feeTypeName: 'Annual Day Kit & Prize Distribution Gala Entry',
    amount: 1000,
    paymentMode: 'upi',
    transactionRef: 'UPI/384729103948',
    date: '2026-03-18',
    time: '04:00 PM',
    academicYear: '2026',
    sessionOrEventYear: 'Session 2026-27',
    remarks: 'Annual Day Delegate Kit & Prize Distribution Gala Entry',
    collectedByStaffName: 'Ramesh Sharma (Counter)',
    collectedByStaffId: 'staff-02',
    approvalStatus: 'PENDING_APPROVAL',
  },
  {
    id: 'xf-04',
    receiptNo: 'XREC-2026-0004',
    studentId: 'stu-03',
    studentRollNo: 'SRIIT0013',
    studentName: 'Amit Kumar Singh',
    courseName: 'Full Stack Web Development (MERN & Next.js)',
    feeCategory: 'FORM_FILLUP',
    feeType: 'FORM_FILLUP',
    feeTitle: 'Special Assessment Form Fillup & Practical Exam Slot',
    feeTypeName: 'Special Assessment Form Fillup & Practical Exam Slot',
    amount: 500,
    paymentMode: 'cash',
    date: '2026-03-19',
    time: '03:45 PM',
    academicYear: '2026',
    sessionOrEventYear: 'Session 2026-27',
    remarks: 'Backlog React & Node Practical Exam Form Fillup',
    collectedByStaffName: 'Pooja Verma (Counter)',
    collectedByStaffId: 'staff-01',
    approvalStatus: 'PENDING_APPROVAL',
  },
  {
    id: 'xf-05',
    receiptNo: 'XREC-2026-0005',
    studentId: 'stu-05',
    studentRollNo: 'SRIIT0015',
    studentName: 'Vikram Choudhury',
    courseName: 'Graphic Design Masterclass (Photoshop, Illustrator, Canva)',
    feeCategory: 'CERTIFICATE_FEE',
    feeType: 'CERTIFICATE_FEE',
    feeTitle: 'Expedited Certificate Verification & Hardcopy Dispatch',
    feeTypeName: 'Expedited Certificate Verification & Hardcopy Dispatch',
    amount: 300,
    paymentMode: 'upi',
    transactionRef: 'UPI/559281042398',
    date: '2026-03-15',
    time: '12:10 PM',
    academicYear: '2026',
    sessionOrEventYear: 'Session 2026-27',
    remarks: 'Urgent certificate dispatch and verification charge',
    collectedByStaffName: 'Pooja Verma (Counter)',
    collectedByStaffId: 'staff-01',
    approvalStatus: 'APPROVED',
    approvedByAdminId: 'admin-01',
    approvedByAdminName: 'Dr. Rajeshwar Patra (Director)',
    approvalDate: '2026-03-15 04:00 PM',
  },
];

export const INITIAL_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'tpl-due-reminder',
    title: 'Installment Fee Due Reminder',
    template:
      'Dear {studentName} ({rollNo}),\n\nThis is a reminder from {instituteName} that your {courseName} fee installment of {amount} is scheduled due on {dueDate}. Kindly clear the pending fee at the fee collection counter or online.\n\nUPI: {upiId}\nBank: {bankName} (A/C: {accountNo}, IFSC: {ifscCode})\n\nRegards,\nAccounts Wing, {instituteName}',
  },
  {
    id: 'tpl-overdue-alert',
    title: 'Overdue Fee Notice',
    template:
      'URGENT NOTICE: Dear {studentName} ({rollNo}),\n\nYour course installment fee of {amount} for {courseName} is OVERDUE since {dueDate}. Please visit the fee desk or pay online via UPI ({upiId}) today to avoid biometric attendance hold.\n\nRegards,\nAccounts Office, {instituteName}',
  },
  {
    id: 'tpl-formfillup-notice',
    title: 'Exam Form Fillup Notification',
    template:
      'Dear {studentName} ({rollNo}),\n\nYour course duration for {courseName} has ended. The semester re-attempt examination / assessment form fillup counter is now open at {instituteName}.\n\nForm Fillup Fee: ₹500\nCounter Hours: 08:00 AM - 06:00 PM\n\nExamination Wing,\n{instituteName}',
  },
  {
    id: 'tpl-annualday-invite',
    title: 'Annual Day Registration',
    template:
      'Dear {studentName} ({rollNo}),\n\n{instituteName} cordially invites you to the Annual Day Celebrations & Award Ceremony! Delegate registrations and event passes are now being collected at the desk.\n\nAnnual Day Kit & Dinner: ₹1,000\n\nBest Wishes,\nCultural Committee,\n{instituteName}',
  },
];


